swagger: '2.0'
host: swagger.io
basePath: /
info:
  title: Better API Tutorial
  description: This is a better API.
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Support
    url: http://www.swagger.io/support
    email: support@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

schemes:
 - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /talks:
    post:
      summary: Add talk to DB
      description: Results in new talk information added to the DB
      parameters:      
        - name: talk
          in: body
          description: Talk details
          schema:
            description: Talk schema
            required: [title, talkDescription]
            properties:
              title:
                type: string
                description: The title of talk
              talkDescription:
                type: string
                description: The description of talk
      responses:
        201:
          description: Created new talk in the database
          schema:
            required: [talk-id]
            properties:
              talk-id:
                type: number
                description: Unique Id for the talk in the system
    get:
      summary: Get a list of talks.
      description: Retrieve a list of talk.
      responses:
        200:
          description: OK
          
  /speakers:
    post:
      summary: Add speaker to DB
      description: Results in new speaker information added to the DB
      parameters:      
        - name: speaker
          in: body
          description: Speaker Details
          schema:
            description: Speaker schema
            required: [firstName, lastName]
            properties:
              firstName:
                type: string
                description: The first name of speaker.
              lastName:
                type: string
                description: The last name of speaker.
      responses:
        201:
          description: Created new speaker in the database
          schema:
            required: [speaker-id]
            properties:
              speaker-id:
                type: number
                description: Unique Id for the speaker in the system
    get:
      summary: Get a list of speakers.
      description: Retrieve a list of speakers.
      responses:
        200:
          description: OK
