swagger: '2.0'
host: swagger.io
basePath: /
info:
  title: Better API Tutorial
  description: This is a better API.
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Support
    url: http://www.swagger.io/support
    email: support@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

schemes:
 - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /talks:
    get:
      summary: Get a list of talks.
      description: Retrieve a list of talk.
      responses:
        200:
          description: OK
  /speakers:
    get:
      summary: Get a list of speakers.
      description: Retrieve a list of speakers.
      responses:
        200:
          description: OK
